### ISSUE TITLE
[chore] 초기 세팅

### ISSUE THREAD

**Issue by dayo2n** [Nexters/Don-t-Forget---iOS#1]
# TODO
- [x] 프로젝트 세팅 @dayo2n 
- [x] gitignore @dayo2n 
- [x] 깃 템플릿 세팅 @jife98 
- [x] 깃, 코드 컨벤션 세팅
